plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.dagger.hilt.android'
    id("com.google.devtools.ksp").version("2.0.0-1.0.22")
    alias(libs.plugins.compose.compiler)

}

apply from: 'version.gradle'

def localProperties = new Properties()
localProperties.load(new FileInputStream(rootProject.file("local.properties")))

android {
    namespace 'me.fernandesleite.mahoulist'
    compileSdk 35

    defaultConfig {
        applicationId "me.fernandesleite.mahoulist"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        debug {
            buildConfigField("String", "CLIENT_ID", localProperties['oauth.client.id'])
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        compose true
        buildConfig = true
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {
    // Compose
    implementation platform(libs.compose.bom)
    implementation libs.compose.ui
    implementation libs.compose.ui.graphics
    implementation libs.compose.ui.tooling.preview
    implementation libs.compose.material3
    implementation libs.compose.material3.icons
    implementation libs.compose.navigation
    implementation libs.lifecycle.viewmodel.compose

    // AndroidX libraries
    implementation libs.core.ktx
    implementation libs.lifecycle.runtime.ktx

    // Hilt
    implementation libs.hilt.android
    ksp libs.hilt.compiler
    implementation libs.hilt.navigation.compose

    // Networking
    implementation libs.retrofit
    implementation libs.retrofit.moshi
    implementation libs.moshi
    implementation libs.moshi.kotlin
    ksp libs.moshi.kotlin.codegen
    implementation libs.okhttp
    implementation libs.okhttp.logging

    // Image loading
    implementation libs.coil
    implementation libs.coil.compose

    // Room
    implementation libs.room.runtime
    ksp libs.room.compiler

    // Testing
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.compose.ui.test.junit4
    debugImplementation libs.compose.ui.tooling
    debugImplementation libs.compose.ui.test.manifest
    testImplementation libs.room.testing
}
